### ISSUE TITLE
Node 8 Support

### ISSUE THREAD

**Issue by nbibler** [chrisguttandin/automation-events#17]
The current `package.json` looks to require Node 10.15.3+:

https://github.com/chrisguttandin/automation-events/blob/29eca9ca430f0508c52f15b4850b55f811356684/package.json#L57-L59

Is there a particular feature used that wouldn't work with Node 8? I'm curious because Node 8 is an [LTS release with support](https://nodejs.org/en/about/releases/) through the end of 2019 (~2 more months):

![Node-LTS](https://user-images.githubusercontent.com/3775/68223278-7dbc4080-ffba-11e9-979d-568855617425.png)

**Comment by chrisguttandin** [comment]
No there is no feature used that I'm aware of which would require Node.js v10. The main reason for setting the engines property is that the TypeScript files get transpiled with Babel for Node.js v10.

https://github.com/chrisguttandin/automation-events/blob/master/config/babel/build.json#L7

Did you try using it with Node.js v8. Did you get any error?

**Comment by chrisguttandin** [comment]
Hi @nbibler, I'm closing this issue now since Node.js v8 reached End-of-live. I will try to keep Node.js v10 support until it reaches its End-of-live and not switch to v12 eagerly this time.
