### ISSUE TITLE
SetTarget event ignores previous SetValue event

### ISSUE THREAD

**Issue by ghost** [chrisguttandin/automation-events#45]
Hello,

It seems a value on SetTarget event after SetValue event does not start transition from the SetValue's value but from default value.

```
const automationEventList = new AutomationEventList(0);
automationEventList.add({ type: "setValue", startTime: 0, value: 1 });
automationEventList.add({
  type: "setTarget",
  startTime: 1,
  target: -1,
  timeConstant: 1
});

automationEventList.getValue(0.5);  // 1 as expected
automationEventList.getValue(1.1);  // -0.095.... not around 1
```

https://codepen.io/mizkichan/pen/poRNmRY

**Comment by chrisguttandin** [comment]
Thanks a lot for making me aware of this and for providing the test case.

I already started typing my response to explain why I think the behavior is correct until a realized that you are absolutely right. The param automation is very complicated. ;-)

**Comment by ghost** [comment]
No problem! Glad I could help you.

**Comment by chrisguttandin** [comment]
Thanks again. v3.0.9 should contain the fix.
