### ISSUE TITLE
Browser key in package.json pointed to a file that doesn't exist

### ISSUE THREAD

**Issue by jthawme** [chrisguttandin/automation-events#57]
I was trying to use tone.js with parcel and it failed on this package, as the `browser` key in package.json pointed to `"build/es5/bundle.js"` which didnt seem to exist in the package

changing it to 

```
"browser": "build/es2019/module.js",
```

seemed to work for me

**Comment by chrisguttandin** [comment]
Thanks for letting me know. It looks like there was a glitch in the build system. The es5 folder is missing in the v6.0.8 release. The v6.0.7 release still has it. I'm trying to investigate why that's the case.

https://www.npmjs.com/package/automation-events/v/6.0.7?activeTab=code
https://www.npmjs.com/package/automation-events/v/6.0.8?activeTab=code

Maybe you have the chance to meanwhile pin automation-events to version 6.0.7.

**Comment by chrisguttandin** [comment]
This commit (https://github.com/chrisguttandin/automation-events/commit/ab8192ba8bd37566e3799fff55036b80fe4d11c2) should have fixed it. v6.0.9 contains all the files again.

Thanks again for making me aware of it.
